create database employee_attirtion;
use employee_attirtion;
select * from employee_attirtion_new ;
describe employee_attirtion_new;
select gender,count(*) from employee_attirtion_new where attrition ='yes' group by gender;
select min(MonthlyIncome) from employee_attirtion_new;
select maritalstatus,count(attrition) from employee_attirtion_new where attrition='yes' group by maritalstatus,attrition;
select attrition,JobSatisfaction,count(attrition) from employee_attirtion_new group by JobSatisfaction,attrition order by JobSatisfaction;
select attrition,count(attrition) from employee_attirtion_new where age between 18 and 40 group by attrition;
select attrition,count(attrition) from employee_attirtion_new where MonthlyIncome between 5000 and 10000 group by attrition;
select avg(age) from employee_attirtion_new where attrition='yes';
alter table employee_attirtion_new add column income_cat varchar(50);
set sql_safe_updates=0;
update employee_attirtion_new set income_cat=case when monthlyincome<=8000 then 'below average' when monthlyincome>8000 and monthlyincome<=15000 then 'average' else 'above average' end;
update employee_attirtion_new set income_cat=case when monthlyincome<=8000 then 'below average' when monthlyincome>8000 and monthlyincome<=15000 then 'average' else 'above average' end;
select income_cat,count(attrition) from employee_attirtion_new where attrition ='yes' group by income_cat;
describe employee_attirtion_new;
select businesstravel,count(*) from employee_attrition_new where attrition='yes' group by businesstravel;
select educationfield,count(attrition) from employee_attrition_new where attrition='Yes' group by educationfield order by count(attrition);
select department,count(attrition) from employee_attrition_new where attrition='Yes' group by department order by count(attrition);
select jobinvolvement,count(attrition) from employee_attirtion_new where attrition='Yes' group by jobinvolvement order by jobinvolvement;